package com.dsh.harness;

import android.content.Context;
import android.util.Log;

import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.util.zip.GZIPInputStream;

/**
 * 首启动引导：
 *   1. 解包预置的 dsh-bundle（usr/bin/node + usr/lib/*.so + home/node_modules）
 *   2. 补可执行权限 / ICU 软链
 *   3. 写 openssl.cnf、建 tmp 目录（Termux 二进制把路径硬编码成 /data/data/com.termux/…）
 *   4. 生成 node 预加载 shim（修正 child_process 默认 shell）
 *   5. 生成启动脚本 dsh-web.sh
 *
 * 布局与 Termux 一致：
 *   $PREFIX = files/usr   -> usr/bin/... , usr/lib/...
 *   $HOME   = files/home  -> home/node_modules/...
 *
 * 注意：Termux 编译的二进制里硬编码了 /data/data/com.termux/files/usr 与 .../home，
 * 本 App 包名是 com.dsh.harness，那些绝对路径既不存在也读不了。
 * 因此凡是能用环境变量覆盖的（OpenSSL/TMPDIR/SHELL）都用环境变量覆盖，
 * 剩下的（child_process 默认 shell）用 NODE_OPTIONS=--require 的 shim 兜住。
 */
public final class DshBootstrap {

    private static final String TAG = "DshBootstrap";
    public static final int DSH_PORT = 3080;
    private static final String STAMP = ".dsh-installed";

    /** bundle 修订号。仅当 bundle 布局/内容变化时才需要改（会触发重新解包）。 */
    private static final String BUNDLE_REV = "v2-usr-home-symlinks";

    /** AGP 会把 assets 里的 .tar.gz 重命名为 .tar，这里两种都试。 */
    private static final String[] BUNDLE_NAMES = {
        "dsh-bundle.tar.gz", "dsh-bundle.tar"
    };
    private static final String PATCH_ASSET = "patch.sh";
    private static volatile String lastError = null;

    /** 上一次解包是否触发了"自动修复"（用于界面显示，便于排障）。 */
    private static volatile String repairNote = null;

    /**
     * 解包完整性抽查清单。
     *
     * 为什么需要：解包器遇到写失败（典型是**存储空间不足**）时只记一条日志就继续，
     * 然后照样写 stamp —— 结果是"永久缺文件"，之后每次升级都因为 stamp 命中而跳过解包。
     * 真机上表现就是 dsh 起得来、能打印 token URL，但 `/` 读 dist/index.html 失败
     * → webserver 返回 404 + **空响应体** → 浏览器只报
     * net::ERR_HTTP_RESPONSE_CODE_FAILURE（完全看不出真因）。
     * 所以每次启动都抽查这些关键文件，缺任何一个就自动重解包。
     */
    private static final String[] CRITICAL_FILES = {
        "usr/bin/node",
        "usr/bin/bash",
        "usr/lib/libc++_shared.so",
        "usr/lib/libicuuc.so.78",
        "usr/lib/libz.so.1",
        "home/node_modules/@deepseek-ai/dsh/lib/bin.js",
        "home/node_modules/@deepseek-ai/dsh-web-app/lib/index.js",
        "home/node_modules/@deepseek-ai/dsh-host-frontend-static/lib/index.js",
        "home/node_modules/@deepseek-ai/dsh-client-connection/lib/index.js",
        "home/node_modules/@deepseek-ai/dsh-web-frontend/dist/index.html",
        "home/node_modules/@deepseek-ai/dsh-web-frontend/dist/manifest.webmanifest",
        "home/node_modules/@koromix/koffi-android-arm64/android_arm64/koffi.node",
    };
    /**
     * dist/assets 下应有的**递归**文件数下限（实际 86）。
     * ⚠️ 必须递归统计：{@code File.list()} 只返回顶层条目，
     * 而 dist/assets 顶层只有 6 项（fonts/、langs/ 两个目录 + 4 个文件），
     * 拿它跟递归数比较会永远误判成"缺失"。
     */
    private static final int CRITICAL_DIST_ASSET_MIN = 60;
    /** 递归统计时的条目上限，防止异常情况下遍历过久。 */
    private static final int COUNT_LIMIT = 4000;
    /**
     * 解包所需的最小可用空间。
     * 解包是流式写盘（先清理旧解包，再写入），峰值只需要 tar 内容的 ~740MB，
     * 这里留 ~160MB 余量取 900MB，避免因为余量给太保守而误拦。
     */
    private static final long MIN_FREE_BYTES = 900L * 1000 * 1000;

    /** 最小的 OpenSSL 3 配置：激活内置 default provider 即可，node 的 TLS 走它。 */
    private static final String OPENSSL_CNF =
        "# generated by DshBootstrap (minimal OpenSSL 3 config)\n"
        + "openssl_conf = openssl_init\n\n"
        + "[openssl_init]\n"
        + "providers = provider_sect\n\n"
        + "[provider_sect]\n"
        + "default = default_sect\n\n"
        + "[default_sect]\n"
        + "activate = 1\n";

    private DshBootstrap() {}

    public static File prefix(Context ctx) { return new File(ctx.getFilesDir(), "usr"); }
    public static File home(Context ctx) { return new File(ctx.getFilesDir(), "home"); }

    /** 上次解包是否触发了自动修复（无则返回 null）。 */
    public static String getRepairNote() { return repairNote; }

    /** app 私有目录的可用空间；失败返回 -1。 */
    public static long usableBytes(Context ctx) {
        try { return ctx.getFilesDir().getUsableSpace(); } catch (Throwable e) { return -1; }
    }

    /**
     * 抽查解包完整性。
     * @return null 表示完好；否则返回缺失项的可读描述。
     */
    private static String checkIntegrity(Context ctx) {
        try {
            File files = ctx.getFilesDir();
            StringBuilder miss = new StringBuilder();
            int count = 0;
            for (String rel : CRITICAL_FILES) {
                // 注意：libicuuc.so.78 / libz.so.1 这类短名是符号链接，
                // exists() 会跟随链接判断，正好是我们想要的效果。
                if (!new File(files, rel).exists()) {
                    if (count++ < 5) miss.append(miss.length() == 0 ? "" : ", ").append(rel);
                }
            }
            File assets = new File(files,
                "home/node_modules/@deepseek-ai/dsh-web-frontend/dist/assets");
            int n = countFiles(assets);
            if (n < CRITICAL_DIST_ASSET_MIN) {
                if (count++ < 5) {
                    miss.append(miss.length() == 0 ? "" : ", ")
                        .append("dist/assets(递归 ").append(n).append(" 个文件)");
                }
            }
            if (count == 0) return null;
            String s = miss.toString();
            return count > 5 ? s + " 等 " + count + " 项" : s;
        } catch (Throwable e) {
            return "抽查异常 " + e;
        }
    }

    /**
     * 递归统计目录下的**文件**数（不含目录本身，遇目录继续下钻）。
     * 用迭代而非递归，避免异常深目录把栈打爆；总数受 {@link #COUNT_LIMIT} 限制。
     */
    private static int countFiles(File dir) {
        if (!dir.isDirectory()) return 0;
        int files = 0;
        java.util.ArrayDeque<File> stack = new java.util.ArrayDeque<File>();
        stack.push(dir);
        int seen = 0;
        while (!stack.isEmpty() && seen < COUNT_LIMIT) {
            File cur = stack.pop();
            File[] kids = cur.listFiles();
            if (kids == null) continue;
            for (File kid : kids) {
                if (seen++ >= COUNT_LIMIT) break;
                if (kid.isDirectory()) stack.push(kid);
                else files++;
            }
        }
        return files;
    }

    /**
     * 生成一份可读的完整性清单，直接显示在界面上。
     * 排障时最费时间的就是"到底哪个文件没了"，这里一次列全，省掉来回猜测。
     */
    public static String describeIntegrity(Context ctx) {
        StringBuilder sb = new StringBuilder();
        File files = ctx.getFilesDir();
        sb.append("【关键文件清单】\n");
        for (String rel : CRITICAL_FILES) {
            File f = new File(files, rel);
            sb.append(f.exists()
                ? "  [有] " + f.length() + " 字节  " + rel + "\n"
                : "  [缺] " + rel + "\n");
        }
        File assets = new File(files,
            "home/node_modules/@deepseek-ai/dsh-web-frontend/dist/assets");
        String[] top = assets.isDirectory() ? assets.list() : null;
        sb.append("  dist/assets 顶层条目: ").append(top == null ? 0 : top.length)
          .append("，递归文件数: ").append(countFiles(assets))
          .append("（阈值 ").append(CRITICAL_DIST_ASSET_MIN).append("）\n");
        return sb.toString();
    }

    public static void setupIfNeeded(Context ctx) {
        File stamp = new File(ctx.getFilesDir(), STAMP);
        boolean needExtract = !stamp.exists() || !BUNDLE_REV.equals(readStamp(stamp));

        // stamp 命中 ≠ 文件齐全：解包中途写失败（多为空间不足）会留下"永久残档"。
        // 这里每次启动都抽查若干关键文件，缺任何一个就自动修复重解包。
        if (!needExtract) {
            String missing = checkIntegrity(ctx);
            if (missing != null) {
                Log.w(TAG, "解包完整性抽查未通过 → 自动修复重解包: " + missing);
                repairNote = "上次解包不完整（" + missing + "），已自动重新解包。";
                needExtract = true;
            }
        }

        try {
            if (needExtract) {
                // 先确认空间够再动旧解包：否则清理完才发现空间不足，用户两头空。
                long free = usableBytes(ctx);
                Log.i(TAG, "需要解包，当前可用空间: " + (free / 1048576) + " MB");
                if (free >= 0 && free < MIN_FREE_BYTES) {
                    throw new Exception("存储空间不足：解包需要约 " + (MIN_FREE_BYTES / 1048576)
                        + " MB 可用空间，当前只有 " + (free / 1048576) + " MB。请先清理空间再重试。");
                }
                if (stamp.exists()) {
                    Log.i(TAG, "bundle 修订号变化，清理旧解包");
                    cleanupExtracted(ctx);
                    stamp.delete();
                }
                extractBundle(ctx);
                fixBinPermissions(ctx);
                relinkLibs(ctx);
                ensureIcuLinks(ctx);
                File patch = new File(ctx.getFilesDir(), PATCH_ASSET);
                if (patch.exists()) {
                    patch.setExecutable(true);
                    ShellRunner.exec(ctx, "bash " + patch.getAbsolutePath());
                }
                writeStamp(stamp, BUNDLE_REV);
                Log.i(TAG, "解包完成 rev=" + BUNDLE_REV);
            }

            // 每次启动都做的轻量修护：升级 APK 后无需重新解包 700MB
            fixBinPermissions(ctx);
            ensureIcuLinks(ctx);
            ensureKoffiNative(ctx);
            writeOpensslConf(ctx);
            createLauncher(ctx);
            Log.i(TAG, "bootstrap ready rev=" + BUNDLE_REV);
        } catch (Throwable e) {
            // 绝不能吞异常：把真实原因存下来，由界面显示给用户（无法 adb 时唯一渠道）
            lastError = e.getClass().getSimpleName() + ": " + e.getMessage();
            if (e.getStackTrace().length > 0) {
                lastError += "\n  at " + e.getStackTrace()[0];
            }
            Log.e(TAG, "bootstrap 失败", e);
        }
    }

    /** 解包 assets 里的 bundle，并按 gzip 魔数判断是否需要 gunzip。 */
    private static void extractBundle(Context ctx) throws Exception {
        String found = null;
        for (String name : BUNDLE_NAMES) {
            try {
                ctx.getAssets().open(name).close();
                found = name;
                break;
            } catch (Exception ignored) { }
        }
        if (found == null) {
            lastError = "assets 里找不到 dsh-bundle。\n包内实际资源：" + listAssets(ctx);
            Log.e(TAG, "assets 里找不到 dsh-bundle");
            return;
        }
        Log.i(TAG, "解包 " + found);
        InputStream in = ctx.getAssets().open(found);
        try {
            final int[] count = { 0 };
            final long[] lastReport = { 0 };
            ProgressListener listener = new ProgressListener() {
                @Override public void onProgress(int files, long bytes) {
                    count[0] = files;
                    long now = System.currentTimeMillis();
                    if (now - lastReport[0] > 1500) {
                        lastReport[0] = now;
                        Log.i(TAG, "解包中: " + files + " 个文件, " + (bytes / 1048576) + " MB");
                    }
                }
            };
            InputStream raw = new BufferedInputStream(in);
            raw.mark(2);
            int magic1 = raw.read();
            int magic2 = raw.read();
            raw.reset();
            boolean isGzip = (magic1 == 0x1f && magic2 == 0x8b);
            Log.i(TAG, "bundle=" + found + " gzip魔数=" + (isGzip ? "有效" : "无效"));
            if (isGzip) {
                TarGz.extract(new GZIPInputStream(raw), ctx.getFilesDir(), listener);
            } else {
                TarGz.extract(raw, ctx.getFilesDir(), listener);
            }
            Log.i(TAG, "解包完成，共 " + count[0] + " 个条目，跳过 " + TarGz.skippedCount);
            // 有关键条目没写成功就绝不能写 stamp —— 否则会留下永久残档，
            // 之后每次升级都因 stamp 命中而跳过解包（真机上的连环坑正是这么来的）。
            if (TarGz.skippedCount > 0) {
                throw new Exception("解包时有 " + TarGz.skippedCount
                    + " 个文件写入失败（通常是存储空间不足）。已中止安装标记，下次启动会重试。");
            }
            String missing = checkIntegrity(ctx);
            if (missing != null) {
                throw new Exception("解包后完整性抽查未通过：" + missing
                    + "。已中止安装标记，下次启动会重试。");
            }
        } finally {
            try { in.close(); } catch (Exception ignored) { }
        }
    }

    private static void fixBinPermissions(Context ctx) {
        File binDir = new File(prefix(ctx), "bin");
        File[] bins = binDir.listFiles();
        if (bins != null) for (File f : bins) if (f.isFile()) f.setExecutable(true);
    }

    /** 写 openssl.cnf 并建 tmp 目录 —— Termux 二进制默认路径不可用，必须显式指定。 */
    private static void writeOpensslConf(Context ctx) {
        try {
            File tlsDir = new File(prefix(ctx), "etc/tls");
            tlsDir.mkdirs();
            File conf = new File(tlsDir, "openssl.cnf");
            if (!conf.exists() || conf.length() != OPENSSL_CNF.length()) {
                java.io.FileWriter fw = new java.io.FileWriter(conf);
                try { fw.write(OPENSSL_CNF); } finally { fw.close(); }
            }
            new File(prefix(ctx), "tmp").mkdirs();
            new File(prefix(ctx), "var/tmp").mkdirs();
        } catch (Exception e) {
            Log.w(TAG, "写 openssl.cnf / tmp 目录失败", e);
        }
    }

    private static String readStamp(File f) {
        try {
            return new String(java.nio.file.Files.readAllBytes(f.toPath()), "UTF-8").trim();
        } catch (Exception e) {
            return null;
        }
    }

    private static void writeStamp(File f, String v) {
        try {
            java.nio.file.Files.write(f.toPath(), v.getBytes("UTF-8"));
        } catch (Exception ignored) { }
    }

    /** 清理上一次解包产物（含扁平布局残留），确保重新解包是干净的。 */
    private static void cleanupExtracted(Context ctx) {
        File dir = ctx.getFilesDir();
        for (String n : new String[] { "usr", "home", "bin", "lib", "node_modules" }) {
            deleteRecursively(new File(dir, n));
        }
    }

    private static void deleteRecursively(File f) {
        if (f == null || !f.exists()) return;
        if (f.isDirectory()) {
            File[] cs = f.listFiles();
            if (cs != null) for (File c : cs) deleteRecursively(c);
        }
        try { f.delete(); } catch (Exception ignored) { }
    }

    /** 列出 APK 里的 assets，排查打包问题。 */
    private static String listAssets(Context ctx) {
        try {
            String[] a = ctx.getAssets().list("");
            StringBuilder sb = new StringBuilder();
            if (a != null) for (String s : a) sb.append("  ").append(s).append('\n');
            return sb.length() == 0 ? "  （assets 为空）" : sb.toString();
        } catch (Exception e) {
            return "  （无法读取: " + e.getMessage() + "）";
        }
    }

    /** 最近一次 bootstrap 失败的原因（供 UI 显示），null 表示成功。 */
    public static String getLastError() {
        return lastError;
    }

    /** Windows 上打的 tar 会把符号链接存成 0 字节文件，这里按版本号重建（兜底）。 */
    private static void relinkLibs(Context ctx) {
        File libDir = new File(prefix(ctx), "lib");
        File[] files = libDir.listFiles();
        if (files == null) return;
        for (File f : files) {
            if (f.length() != 0 || f.isDirectory()) continue;
            String name = f.getName();
            int dot = name.indexOf(".so");
            if (dot < 0) continue;
            String base = name.substring(0, dot + 3);
            File[] sib = libDir.listFiles();
            if (sib == null) continue;
            for (File s : sib) {
                if (s.isFile() && s.length() > 0 && s.getName().startsWith(base)
                        && !s.getName().equals(name)) {
                    try {
                        java.nio.file.Files.createSymbolicLink(
                            f.toPath(), new File(libDir, s.getName()).toPath());
                        Log.i(TAG, "重建符号链接 " + name + " -> " + s.getName());
                    } catch (Exception ignored) { }
                    break;
                }
            }
        }
    }

    /** node 依赖无版本名的 ICU 入口（兜底；bundle 已含真软链）。 */
    private static void ensureIcuLinks(Context ctx) {
        File libDir = new File(prefix(ctx), "lib");
        String[][] pairs = {
            {"libicuuc.so.78", "libicuuc.so.78.3"},
            {"libicui18n.so.78", "libicui18n.so.78.3"},
            {"libicudata.so.78", "libicudata.so.78.3"},
        };
        for (String[] p : pairs) {
            File link = new File(libDir, p[0]);
            File real = new File(libDir, p[1]);
            if (!real.exists()) continue;
            if (link.exists() && link.length() > 0) continue;
            try {
                if (link.exists()) link.delete();
                java.nio.file.Files.createSymbolicLink(link.toPath(), real.toPath());
                Log.i(TAG, "补 ICU 软链 " + p[0] + " -> " + p[1]);
            } catch (Exception e) {
                try {
                    java.nio.file.Files.copy(real.toPath(), link.toPath(),
                        java.nio.file.StandardCopyOption.REPLACE_EXISTING);
                    Log.i(TAG, "复制 ICU 库 " + p[0]);
                } catch (Exception e2) {
                    Log.e(TAG, "ICU 软链与复制都失败: " + p[0], e2);
                }
            }
        }
    }

    /**
     * node 预加载 shim：Termux 版 node 把 child_process 的默认 shell 编译成
     * /data/data/com.termux/files/usr/bin/sh（本 App 不可用），这里统一改成 $PREFIX/bin/bash。
     * 用 ES5 写，避免任何语法问题导致 node 起不来。
     */
    private static final String NODE_SHIM =
        "// generated by DshBootstrap\n"
        + "(function () {\n"
        + "  try {\n"
        + "    var cp = require('child_process');\n"
        + "    var BASH = (process.env.PREFIX || '') + '/bin/bash';\n"
        + "    var TMUX = '/data/data/com.termux/';\n"
        + "    function pick(o, isExec) {\n"
        + "      if (o === null || typeof o !== 'object' || Array.isArray(o)) o = {};\n"
        + "      if (typeof o.shell === 'string') {\n"
        + "        if (o.shell.indexOf(TMUX) === 0) o.shell = BASH;\n"
        + "      } else if (o.shell === true || (o.shell === undefined && isExec)) {\n"
        + "        o.shell = BASH;\n"
        + "      }\n"
        + "      return o;\n"
        + "    }\n"
        + "    var _exec = cp.exec;\n"
        + "    cp.exec = function (command, options, callback) {\n"
        + "      if (typeof options === 'function') { callback = options; options = {}; }\n"
        + "      return _exec.call(this, command, pick(options, true), callback);\n"
        + "    };\n"
        + "    var _execSync = cp.execSync;\n"
        + "    cp.execSync = function (command, options) {\n"
        + "      return _execSync.call(this, command, pick(options, true));\n"
        + "    };\n"
        + "    var _execFile = cp.execFile;\n"
        + "    cp.execFile = function (file, args, options, callback) {\n"
        + "      if (typeof args === 'function') { callback = args; args = []; options = {}; }\n"
        + "      else if (!Array.isArray(args)) { if (args && typeof args === 'object') options = args; args = []; }\n"
        + "      if (typeof options === 'function') { callback = options; options = {}; }\n"
        + "      return _execFile.call(this, file, args, pick(options, false), callback);\n"
        + "    };\n"
        + "    var _execFileSync = cp.execFileSync;\n"
        + "    cp.execFileSync = function (file, args, options) {\n"
        + "      if (!Array.isArray(args)) { if (args && typeof args === 'object') options = args; args = []; }\n"
        + "      return _execFileSync.call(this, file, args, pick(options, false));\n"
        + "    };\n"
        + "    var _spawn = cp.spawn;\n"
        + "    cp.spawn = function (command, args, options) {\n"
        + "      if (!Array.isArray(args)) { if (args && typeof args === 'object') options = args; args = []; }\n"
        + "      return _spawn.call(this, command, args, pick(options, false));\n"
        + "    };\n"
        + "    var _spawnSync = cp.spawnSync;\n"
        + "    cp.spawnSync = function (command, args, options) {\n"
        + "      if (!Array.isArray(args)) { if (args && typeof args === 'object') options = args; args = []; }\n"
        + "      return _spawnSync.call(this, command, args, pick(options, false));\n"
        + "    };\n"
        + "  } catch (e) { }\n"
        + "})();\n";

    /**
     * 补齐 koffi 的原生模块。
     *
     * bundle 里只有 @koromix/koffi-android-arm64/android_arm64/koffi.node，
     * 而 koffi 的加载器只在两处找本机二进制：
     *   1) node_modules/@koromix/koffi-<platform>-<arch>（platform 报 android 时命中）
     *   2) node_modules/koffi/build/koffi/<platform>_<abi>/koffi.node（"<abi>" = process.arch）
     * Termux 的 node 可能报告 platform=linux 也可能报 android，两种都覆盖。
     * 缺失时 dsh 整个 cordis profile 加载失败并抛
     * "Cannot find the native Koffi module"，对外表现就是根路径 401 / 无响应。
     */
    private static void ensureKoffiNative(Context ctx) {
        try {
            File nm = new File(home(ctx), "node_modules");
            File srcAndroid = new File(nm, "@koromix/koffi-android-arm64/android_arm64/koffi.node");
            File srcLinux = new File(nm, "@koromix/koffi-linux-arm64/linux_arm64/koffi.node");
            File src = null;
            if (srcAndroid.exists() && srcAndroid.length() > 0) src = srcAndroid;
            else if (srcLinux.exists() && srcLinux.length() > 0) src = srcLinux;
            if (src == null) {
                Log.w(TAG, "找不到 koffi 原生模块来源，跳过补齐（node_modules/@koromix 不存在？）");
                return;
            }
            String[] variants = {"android_arm64", "linux_arm64"};
            for (String variant : variants) {
                File dir = new File(nm, "koffi/build/koffi/" + variant);
                File dst = new File(dir, "koffi.node");
                if (dst.exists() && dst.length() == src.length()) continue;
                dir.mkdirs();
                copyFile(src, dst);
                dst.setReadable(true, false);
                dst.setExecutable(true, false);
            }
            Log.i(TAG, "koffi 原生模块已就位 (" + src.length() + " 字节)");
        } catch (Throwable e) {
            Log.e(TAG, "补齐 koffi 原生模块失败", e);
        }
    }

    private static void copyFile(File src, File dst) throws Exception {
        java.io.InputStream in = new java.io.FileInputStream(src);
        try {
            java.io.OutputStream out = new java.io.FileOutputStream(dst);
            try {
                byte[] buf = new byte[65536];
                int n;
                while ((n = in.read(buf)) > 0) out.write(buf, 0, n);
            } finally { out.close(); }
        } finally { in.close(); }
    }

    private static void createLauncher(Context ctx) throws Exception {
        String p = prefix(ctx).getAbsolutePath();
        String h = home(ctx).getAbsolutePath();

        File homeDir = home(ctx);
        homeDir.mkdirs();
        new File(homeDir, ".tmp").mkdirs();
        new File(homeDir, ".cache").mkdirs();

        // node 预加载 shim
        File libexec = new File(p, "libexec");
        libexec.mkdirs();
        File shim = new File(libexec, "dsh-node-shim.js");
        if (!shim.exists() || shim.length() != NODE_SHIM.length()) {
            java.io.FileWriter fw = new java.io.FileWriter(shim);
            try { fw.write(NODE_SHIM); } finally { fw.close(); }
        }

        File launcher = new File(p, "bin/dsh-web.sh");
        launcher.getParentFile().mkdirs();
        StringBuilder sb = new StringBuilder();
        sb.append("#!/bin/bash\n");
        sb.append("# 由 DshBootstrap 自动生成：启动 dsh Web 服务\n");
        sb.append("export PREFIX=\"").append(p).append("\"\n");
        sb.append("export HOME=\"").append(h).append("\"\n");
        sb.append("mkdir -p \"$HOME/.tmp\" \"$HOME/.cache\" \"$PREFIX/tmp\" \"$PREFIX/var/tmp\" 2>/dev/null\n");
        sb.append("export PATH=\"$PREFIX/bin:$PATH\"\n");
        sb.append("export LD_LIBRARY_PATH=\"$PREFIX/lib:$LD_LIBRARY_PATH\"\n");
        // ↓ Termux 二进制里这些路径都被硬编码成 /data/data/com.termux/…，必须覆盖
        sb.append("export SHELL=\"$PREFIX/bin/bash\"\n");
        sb.append("export TMPDIR=\"$PREFIX/tmp\"\n");
        sb.append("export SQLITE_TMPDIR=\"$PREFIX/tmp\"\n");
        sb.append("export OPENSSL_CONF=\"$PREFIX/etc/tls/openssl.cnf\"\n");
        sb.append("export OPENSSL_MODULES=\"$PREFIX/lib/ossl-modules\"\n");
        sb.append("export NODE_OPTIONS=\"--require $PREFIX/libexec/dsh-node-shim.js\"\n");
        sb.append("cd \"").append(h).append("\"\n");
        // --expose-internals：web profile 的 patchReload=live 会创建 cordis-plugin-hmr，
        //   缺这个 flag 它会抛 "--expose-internals is required for HMR service" 并让整个进程退出。
        // --no-open：Termux 里没有 xdg-open，开浏览器必然失败。
        sb.append("exec \"").append(p).append("/bin/node\" --expose-internals \"").append(h)
          .append("/node_modules/@deepseek-ai/dsh/lib/bin.js\" web --port ")
          .append(DSH_PORT).append(" --no-open\n");
        java.io.FileWriter fw = new java.io.FileWriter(launcher);
        try {
            fw.write(sb.toString());
        } finally {
            fw.close();
        }
        launcher.setExecutable(true);
    }

    /** 极简 tar 解包器（ustar + GNU 长名 'L'/'K' + 符号链接 '2' + base-256 大小）。 */
    interface ProgressListener {
        void onProgress(int files, long bytes);
    }

    static final class TarGz {
        /** 本次解包中写入失败的条目数（>0 表示解包不完整，绝不能写 stamp）。 */
        static int skippedCount = 0;

        static void extract(InputStream input, File dest, ProgressListener listener) throws Exception {
            skippedCount = 0;
            BufferedInputStream buf = new BufferedInputStream(input);
            byte[] header = new byte[512];
            String pendingLongName = null;
            String pendingLongLink = null;
            int fileCount = 0;
            long totalBytes = 0;

            while (true) {
                if (!readFully(buf, header)) break;
                if (header[0] == 0) break;

                char typeflag = (char) (header[156] & 0xFF);
                long size = readSize(header, 124, 12);
                String name = pendingLongName != null ? pendingLongName : readName(header);
                pendingLongName = null;
                String linkTarget = pendingLongLink;
                pendingLongLink = null;

                if (typeflag == 'L') {
                    pendingLongName = readDataAsString(buf, size);
                    continue;
                } else if (typeflag == 'K') {
                    pendingLongLink = readDataAsString(buf, size);
                    continue;
                } else if (typeflag == '2') {
                    // 符号链接：Termux 的 .so 短名全靠它（libz.so.1 -> libz.so.1.3.2）
                    String target = linkTarget != null ? linkTarget : cstr(header, 157, 100);
                    File link = new File(dest, name);
                    if (link.getParentFile() != null) link.getParentFile().mkdirs();
                    try {
                        if (link.exists()) link.delete();
                        java.nio.file.Files.createSymbolicLink(link.toPath(),
                            java.nio.file.Paths.get(target));
                        fileCount++;
                    } catch (Exception e) {
                        try {
                            File src = new File(link.getParentFile(), target);
                            java.nio.file.Files.copy(src.toPath(), link.toPath(),
                                java.nio.file.StandardCopyOption.REPLACE_EXISTING);
                            fileCount++;
                        } catch (Exception e2) {
                            skippedCount++;
                            Log.w(TAG, "符号链接失败: " + name + " -> " + target
                                + " (" + e.getMessage() + ")");
                        }
                    }
                    skipBlocks(buf, size);
                } else if (typeflag == '5') {
                    new File(dest, name).mkdirs();
                    skipBlocks(buf, size);
                } else if (typeflag == '0' || typeflag == '\0') {
                    File file = new File(dest, name);
                    if (file.getParentFile() != null) file.getParentFile().mkdirs();
                    if (file.isDirectory()) {
                        skipBlocks(buf, size);
                        continue;
                    }
                    try {
                        extractFile(buf, file, size);
                    } catch (java.io.FileNotFoundException e) {
                        skippedCount++;
                        Log.w(TAG, "跳过无法写入的条目: " + name + " (" + e.getMessage() + ")");
                        skipBlocks(buf, size);
                        continue;
                    }
                    if ((readSize(header, 100, 8) & 0077) != 0) file.setExecutable(true);
                    fileCount++;
                    totalBytes += size;
                    if (listener != null) listener.onProgress(fileCount, totalBytes);
                } else {
                    skipBlocks(buf, size);
                }
            }
        }

        private static String readName(byte[] h) {
            // ustar：name(100) + prefix(155)，超长路径会被拆两段，必须拼接
            String name = cstr(h, 0, 100);
            String prefix = cstr(h, 345, 155);
            if (!prefix.isEmpty()) return prefix + "/" + name;
            return name;
        }

        private static String cstr(byte[] b, int off, int len) {
            int end = off;
            int max = off + len;
            while (end < max && b[end] != 0) end++;
            return new String(b, off, end - off);
        }

        private static long readSize(byte[] b, int off, int len) {
            if ((b[off] & 0x80) != 0) {
                long v = 0;
                for (int i = off; i < off + len; i++) v = (v << 8) | (b[i] & 0xFFL);
                return v & 0x7FFFFFFFFFFFFFFFL;
            }
            long s = 0;
            for (int i = off; i < off + len; i++) {
                byte c = b[i];
                if (c == ' ' || c == 0) break;
                s = s * 8 + (c - '0');
            }
            return s;
        }

        private static boolean readFully(BufferedInputStream s, byte[] buf) throws Exception {
            int read = 0;
            while (read < buf.length) {
                int n = s.read(buf, read, buf.length - read);
                if (n < 0) return false;
                read += n;
            }
            return true;
        }

        private static String readDataAsString(BufferedInputStream s, long size) throws Exception {
            java.io.ByteArrayOutputStream out = new java.io.ByteArrayOutputStream();
            long remaining = size;
            byte[] data = new byte[512];
            while (remaining > 0) {
                readFully(s, data);
                int take = (int) Math.min(512, remaining);
                out.write(data, 0, take);
                remaining -= 512;
            }
            String s2 = new String(out.toByteArray());
            int z = s2.indexOf('\0');
            return z >= 0 ? s2.substring(0, z) : s2;
        }

        private static void extractFile(BufferedInputStream s, File file, long size) throws Exception {
            FileOutputStream out = new FileOutputStream(file);
            try {
                long remaining = size;
                byte[] data = new byte[512];
                while (remaining > 0) {
                    int take = (int) Math.min(512, remaining);
                    readFully(s, data);
                    out.write(data, 0, take);
                    remaining -= 512;
                }
            } finally {
                out.close();
            }
        }

        private static void skipBlocks(BufferedInputStream s, long size) throws Exception {
            long blocks = (size + 511) / 512;
            byte[] data = new byte[512];
            for (long i = 0; i < blocks; i++) readFully(s, data);
        }
    }
}
